version: "3"
services:
  proxyweb:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        HOST_FOLDER: "./proxyweb"
        BUILD_CMD: "yarn && yarn build"
        NIX_FILE: "./docker/node.nix"
    environment:
      COMMAND: "yarn && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - "./proxyweb:/workspace/serv"
      - "/workspace/serv/node_modules"
    network_mode: "host"

  authweb:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        HOST_FOLDER: "./authweb"
        BUILD_CMD: "yarn"
        # BUILD_CMD: "yarn && yarn build"
        NIX_FILE: "./docker/node.nix"
    environment:
      COMMAND: "yarn && yarn dev"
    ports:
      - 3001:3000
    network_mode: "host"
    profiles:
      - cloud

  backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        HOST_FOLDER: "./backend"
        BUILD_CMD: "go build -tags line_example"
        NIX_FILE: "./docker/go.nix"
    environment:
      COMMAND: "go run -tags=line ."
    volumes:
      - "./data:/workspace/serv/data"
      - "./backend:/workspace/serv"
    ports:
      - 8000:8000
      - 9000:9000
      - 8080:8080
    env_file:
      - ./backend/basic.env
      - ./backend/secret.env
    network_mode: "host"
