version: '3'
services:
  proxyweb:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        HOST_FOLDER: "./proxyweb"
        BUILD_CMD: "echo hello"
        NIX_FILE: "./docker/node.nix"
    environment:
      COMMAND: yarn dev
      # COMMAND: yarn run
    ports:
      - 3000:3000
    network_mode: "host"

  authweb:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        HOST_FOLDER: "./authweb"
        BUILD_CMD: "yarn build"
        NIX_FILE: "./docker/node.nix"
    environment:
      COMMAND: yarn dev
      # COMMAND: yarn run
    ports:
      - 3001:3000
    network_mode: "host"

  backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        HOST_FOLDER: "./backend"
        BUILD_CMD: "go build"
        NIX_FILE: "./docker/go.nix"
    volumes:
      - "./data:/workspace/serv/data"
    environment:
      COMMAND: go test -run TestIntegration
      # COMMAND: yarn run
    ports:
      - 8000:8000
      - 9000:9000
    env_file:
      - ./backend/basic.env
      - ./backend/secret.env
    network_mode: "host"
