version: "3"
services:
  proxy:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - "./data:/workspace/serv/data"
      - "./proxy:/workspace/serv"
    ports:
      - 8000:8000
      - 8080:8080
      - 9000:9000
    env_file:
      - ./backend/basic.env
      - ./backend/secret.env
