version: "3"
services:
  torima:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - "./data:/workspace/data"
      - "./config.yaml:/workspace/config.yaml"
    ports:
      - 8080:8080
    env_file:
      - ./secret.env
