version: '3'
services:
  proxyweb:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        HOST_FOLDER: "./proxyweb"
        BUILD_CMD: "yarn"
        # BUILD_CMD: "yarn && yarn build"
        NIX_FILE: "./docker/node.nix"
    environment:
      COMMAND: yarn dev
      # COMMAND: yarn run
    ports:
      - 3000:3000
    network_mode: "host"
    profiles:
      - default

  authweb:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        HOST_FOLDER: "./authweb"
        BUILD_CMD: "yarn"
        # BUILD_CMD: "yarn && yarn build"
        NIX_FILE: "./docker/node.nix"
    environment:
      COMMAND: yarn dev
      # COMMAND: yarn run
    ports:
      - 3001:3000
    network_mode: "host"
    profiles:
      - cloud

  backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        HOST_FOLDER: "./backend"
        BUILD_CMD: "go build -tags line_example"
        NIX_FILE: "./docker/go.nix"
    volumes:
      - "./data:/workspace/serv/data"
    environment:
      COMMAND: ./proxy
      # COMMAND: yarn run
    ports:
      - 8000:8000
      - 9000:9000
    env_file:
      - ./backend/basic.env
      - ./backend/secret.env
    network_mode: "host"
    profiles:
      - default

  backend_tee:
    build:
      context: ./
      dockerfile: ./docker/tee/Dockerfile
    volumes:
      - "./data:/workspace/serv/data"
      - "./:/app"
    ports:
      - 8000:8000
      - 9000:9000
    network_mode: "host"
    profiles:
      - tee
