version: '3'
services:
  proxyweb:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        HOST_FOLDER: "./proxyweb"
        BUILD_CMD: "yarn build"
        NIX_FILE: "./docker/node.nix"
    environment:
      COMMAND: yarn dev
      # COMMAND: yarn run
    ports:
      - 3000:3000

  auth:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        HOST_FOLDER: "./auth"
        BUILD_CMD: "yarn build"
        NIX_FILE: "./docker/node.nix"
    environment:
      COMMAND: yarn dev
      # COMMAND: yarn run
    ports:
      - 3001:3000

  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        HOST_FOLDER: "./api"
        BUILD_CMD: "go build"
        NIX_FILE: "./docker/go.nix"
    environment:
      COMMAND: ./proxy
      # COMMAND: yarn run
    ports:
      - 8000:8000
